/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_MEDIATEK_MT6397_AUXADC_H
#define _DT_BINDINGS_MEDIATEK_MT6397_AUXADC_H

#define MT6397_AUXADC_ISENSE		0
#define MT6397_AUXADC_BAT_TEMP		1

#endif
